### ISSUE TITLE
Improvement to unintuitive search options in Advanced Logbook

### ISSUE THREAD

**Issue by xyz667** [wavelog/wavelog#1201]
**By submitting feature requests, you have the opportunity to contribute your ideas and inspiration to the Wavelog Dev-Team. Please be aware that not every feature request will be addressed or answered.**

**What Feature is Missing?**
I suggest improvement to the colouring and placement of buttons in the Advanced Logbook:
- Re-think the layout of buttons and filter fields. There should be an area with search filters, next/close to them the Search button. Currently the search button it is located between other buttons as Edit and Action, that do something to the search results and are not related to searching/filtering.
- In a different section there should be buttons that offer additional search options (Quickfilters, QSL Filters, Filters, Location, maybe also Dupes and Invalid).
- those buttons with additional search options should change to a different color when activated (or another visual indicator).
- there should be a reset button which resets the filters to default.
- maybe relocate the search options and filters to the left side, like on most travel or shopping sites that also have complex search options?

**Why is This Feature Important?**
A Wavelog beginner is easily lost in all those buttons and options in the Advanced Logbook UI, that are somewhat different to how search options on other websites are presented.

**Is This Feature Personal or Beneficial to Others as Well?**
I have missed features in Wavelog because I couldn't find the right button, and I am still a bit lost in the search options. I know at least one other user who is struggeling just like me.

**Comment by HB9HIL** [comment]
Hello @xyz667 

>Re-think the layout of buttons and filter fields. There should be an area with search filters, next/close to them the Search button. Currently the search button it is located between other buttons as Edit and Action, that do something to the search results and are not related to searching/filtering.

The Logbook Advanced is modular. This is why there is a section for filters, quickfilters and action buttons. We and many others really like the layout as it is. In our eyes this is already pretty intuitive.

> In a different section there should be buttons that offer additional search options (Quickfilters, QSL Filters, Filters, Location, maybe also Dupes and Invalid).

As I said in the previous block. It's already grouped and seperated which fits the usage and logic of the workflow.

> there should be a reset button which resets the filters to default.

There is... 

> maybe relocate the search options and filters to the left side, like on most travel or shopping sites that also have complex search options?

This is a layout thing. We currently do not plan to change the layout in general.


> Why is This Feature Important?
A Wavelog beginner is easily lost in all those buttons and options in the Advanced Logbook UI, that are somewhat different to how search options on other websites are presented.
> Is This Feature Personal or Beneficial to Others as Well?
I have missed features in Wavelog because I couldn't find the right button, and I am still a bit lost in the search options. I know at least one other user who is struggeling just like me.

Well, Wavelog brings a huge set of features and functionalities. There is always a gap between "intuitive" UI and the the fact that a user has to get used to it. 

I understand that all the buttons and features in Advanced Logbook can be overwhelming in the first moments of use. But if you use it more often, testing, playing around with buttons, you will see that this make a lot of sense. I don't say that there isn't any room for enhancement. There is - always. But what you asking for is a complete rebuild of Advanced Logbook UI, which is - to be honest - not gonna happen. 

If you have questions, how something is working, where you can find this or that, please use the [discussions area](https://github.com/wavelog/wavelog/discussions). You can place any kind of question there. There are no silly questions, just silly answers. ;-)

**Comment by HB9HIL** [comment]
If you want we can discuss this in more detail, in german: hb9hil@wavelog.org
