### ISSUE TITLE
Add more supported modes to SimpelFLE

### ISSUE THREAD

**Issue by DC1TC** [wavelog/wavelog#315]
SimpleFLE does only support a very limited set of modes. E.g. DIGITALVOICE is not supported.

https://github.com/wavelog/wavelog/blob/f3a8dd68d42e2ec02294afae6230acb73eded460/assets/js/sections/simplefle.js#L469C1-L485C2

The original FLE supports way more modes:

https://df3cb.com/fle/documentation/#modes

**Comment by HB9HIL** [comment]
I agree about this one. I'll add more modes.

**Comment by HB9HIL** [comment]
@DC1TC started working on this in the background. Stay tight. Due to personal reasons you may have to wait a few days. The idea is to not only add some more modes hardcoded in javascript, but to implement all available modes we have already in the database. So we can use this data and have all modes available at a time.

**Comment by HB9HIL** [comment]
@DC1TC  Okay I worked on it earlier then I thought :D You can test #322  if you want. But I want to test it a bit more.

**Comment by HB9HIL** [comment]
@DC1TC We just release Version 1.6. Please test and close this issue if you are happy with it :)

**Comment by DC1TC** [comment]
Just tested with the DF instance on Version 1.6. Works well, thank you!
